[package]
name = "keyboard"
version = "0.1.0"
edition = "2021"

[lib]
name = "keyboard"
crate-type = ["cdylib"]

[dependencies]
crossterm = "*"
cpython = {version = "0.7", features = ["extension-module"]}

