# This is a basic workflow to help you get started with Actions

name: black

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:

  pull_request:


  # Allows you to run this workflow manually from the Actions tab=
jobs:
  black:
    runs-on: ubuntu-latest
    # env:
      # The following variables are available to the workflow
      # Messages:
        # - "${{ github.event.commits[0].message }} - formmated with black"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black codespell
    - name: Check with black
      run: black --preview .
    - name: Commit files  

      run: |
        git config --local user.name  ${{ github.actor }}
  
        git add .
        git commit --allow-empty -m "${{ github.event.commits[0].message }} - formmated with black"
    - name: Push changes  # push the output folder to your repo
      
      uses: actions/github-actions@v2
      with:
        token: ${{ github.token }}
        owner: ${{ github.actor }}
        repo: ${{ github.repo.name }}
        event: push
        branch: ${{ github.ref.split('/')[2] }}
        force: true
        # The following variables are available to the workflow
        # Messages:
        # - "${{ github.event.commits[0].message }} - formmated with black"

