name: python-rust-lib

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:

  pull_request:

jobs:
  rust-to-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable
          override: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools_rust
    - name: build binaries
      run: |
        cd rust
        cd keyboard
        python setup.py build
